verbose: true
branch-master:
    run-option: "after"
    success:
        shell:
            - 'echo "Current user: $USER"'
            - 'rsync -a "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" . deploy@skolporten.se:/mnt/persist/www/2017.skolporten.se'