verbose: true
branch-master:
    run-option: "after"
    success:
        shell:
            - 'echo "Current user: $USER"'
            - 'rsync -rv . deploy@skolporten.se:/mnt/persist/www/2017.skolporten.se'